"""Platform-level seed definitions: international standards, the 18 classification
tests, and the database-driven Rules Repository. These encode the methodology from
the National Framework deck (Parts II-III) and the validation library (workbook
sheet 09). Rules are pure data — the engine in app/engine executes them."""

STANDARDS = [
    {"code": "SNA2025", "name": "System of National Accounts 2025 (with SNA 2008 transition)",
     "issuer": "UN, IMF, OECD, World Bank, Eurostat", "edition": "2025",
     "description": "Institutional sector classification, residence, market/non-market production, ownership and control, enterprise groups.",
     "domains": "National Accounts, Sectorisation, Business Demography"},
    {"code": "GFS2014", "name": "Government Finance Statistics Manual", "issuer": "International Monetary Fund",
     "edition": "2014", "description": "Public-sector boundary; general government vs public corporations; controlled corporations; PPPs and SPVs.",
     "domains": "Government Finance Statistics, Public Sector"},
    {"code": "BPM6", "name": "Balance of Payments and IIP Manual", "issuer": "International Monetary Fund",
     "edition": "6th", "description": "Residence, branches, balance of payments treatment, external sector boundary.",
     "domains": "Balance of Payments, Residence"},
    {"code": "BD4", "name": "OECD Benchmark Definition of Foreign Direct Investment", "issuer": "OECD",
     "edition": "4th", "description": "10% voting threshold, directional principle, ultimate investing country, ultimate controlling institutional unit.",
     "domains": "FDI, Ownership and Control"},
    {"code": "ISIC4", "name": "International Standard Industrial Classification of All Economic Activities",
     "issuer": "United Nations Statistics Division", "edition": "Rev.4",
     "description": "Hierarchical economic-activity coding: section > division > group > class; principal/secondary/ancillary activity.",
     "domains": "Economic Activity, Structural Business Statistics"},
    {"code": "CPC", "name": "Central Product Classification", "issuer": "United Nations Statistics Division", "edition": "2.1",
     "description": "Product classification cross-walked to ISIC.", "domains": "Products, Trade"},
    {"code": "COFOG", "name": "Classification of the Functions of Government", "issuer": "UN/OECD", "edition": "—",
     "description": "Functional classification of government expenditure.", "domains": "Government Finance Statistics"},
    {"code": "ICSE", "name": "International Classification of Status in Employment", "issuer": "ILO", "edition": "ICSE-18",
     "description": "Status-in-employment classification.", "domains": "Labour, Employment"},
    {"code": "SEEA", "name": "System of Environmental-Economic Accounting", "issuer": "UN", "edition": "2012",
     "description": "Environmental-economic accounts; enterprise-level activity attribution.", "domains": "Environment"},
    {"code": "LEI", "name": "Legal Entity Identifier (ISO 17442)", "issuer": "GLEIF / ISO", "edition": "ISO 17442",
     "description": "Globally unique 20-character legal-entity identifier.", "domains": "Identification, Business Register"},
    {"code": "GSIM", "name": "Generic Statistical Information Model", "issuer": "UNECE", "edition": "1.2",
     "description": "Reference framework for statistical information objects and metadata.", "domains": "Metadata, Information Model"},
    {"code": "GSBPM", "name": "Generic Statistical Business Process Model", "issuer": "UNECE", "edition": "5.1",
     "description": "Standard model of the statistical production process.", "domains": "Process"},
    {"code": "SDMX", "name": "Statistical Data and Metadata eXchange", "issuer": "SDMX Initiative", "edition": "3.0",
     "description": "Standards for exchanging statistical data and metadata.", "domains": "Exchange, Dissemination"},
    {"code": "IRIS", "name": "International Recommendations for Industrial Statistics", "issuer": "UNSD", "edition": "2008",
     "description": "Recommendations for industrial statistics.", "domains": "Industrial Statistics"},
    {"code": "IRBR", "name": "International / UNSD-Eurostat Recommendations for Business Registers", "issuer": "UNSD/Eurostat",
     "edition": "—", "description": "Statistical business register units, coverage, and maintenance.", "domains": "Business Register"},
    {"code": "QNCS", "name": "National Classification Standards of Qatar", "issuer": "NSO — State of Qatar", "edition": "1.0",
     "description": "Qatar-specific legal forms, size thresholds and jurisdictional treatment (MoCI, QFC, QFZA).",
     "domains": "National, Business Register"},
]

CONCEPTS = [
    {"standard_code": "SNA2025", "concept": "Institutional unit",
     "definition": "An economic entity capable of owning assets, incurring liabilities, and engaging in economic activities in its own right.",
     "reference": "SNA 2025 Ch.4"},
    {"standard_code": "SNA2025", "concept": "Residence",
     "definition": "An institutional unit is resident where it has its centre of predominant economic interest (≥1 year).",
     "reference": "SNA 2025 Ch.4 / BPM6 Ch.4"},
    {"standard_code": "SNA2025", "concept": "Market producer",
     "definition": "A producer whose sales cover more than 50% of production costs over a sustained period (economically significant prices).",
     "reference": "SNA 2025 — 50% rule"},
    {"standard_code": "GFS2014", "concept": "Public sector boundary",
     "definition": "General government plus public corporations controlled by government.", "reference": "GFS 2014 Ch.2"},
    {"standard_code": "BD4", "concept": "Direct investment relationship",
     "definition": "Established at a 10% voting-power threshold; below is portfolio investment.", "reference": "BD4 §117"},
    {"standard_code": "BD4", "concept": "Ultimate Controlling Institutional Unit (UCI)",
     "definition": "The unit at the top of the ownership chain that is not itself controlled by another unit.", "reference": "BD4 §"},
    {"standard_code": "ISIC4", "concept": "Principal activity",
     "definition": "The activity that generates the largest share of value added.", "reference": "ISIC Rev.4 §"},
]

# test_code, seq (execution order encoding dependencies), name, phase, output dimension
TESTS = [
    ("T1", 10, "Statistical Unit Test", "A. Unit & Residence", None, "Determine the statistical-unit type (10 types).", "SNA2025"),
    ("T2", 20, "Institutional Unit Test", "A. Unit & Residence", None, "Assess institutional substance (7 criteria).", "SNA2025"),
    ("T3", 30, "Residence Test", "A. Unit & Residence", "residence", "Centre of predominant economic interest.", "SNA2025/BPM6"),
    ("T4", 40, "Economic Activity (ISIC) Classification", "B. Activity & Sector", "isic_class", "Principal activity by value added.", "ISIC4"),
    ("T7", 50, "Market vs Non-Market Producer", "B. Activity & Sector", "market_status", "50% rule on production costs.", "SNA2025"),
    ("T8", 60, "Ownership & Effective Control", "C. Control & Scope", "control_flag", "Nine indicators; substance over form.", "BD4/SNA2025"),
    ("T5", 70, "Institutional Sector Classification", "B. Activity & Sector", "sector_code", "Assign to S.11-S.15 / S.2.", "SNA2025"),
    ("T6", 80, "Public Sector Boundary Test", "B. Activity & Sector", "public_private", "Public corporation / general government / private.", "GFS2014"),
    ("T9", 90, "Listed Company Classification", "C. Control & Scope", None, "QSE listing is classification-neutral; reassess control.", "QNCS"),
    ("T10", 100, "Enterprise Size Classification", "C. Control & Scope", "size_class", "Micro/Small/Medium/Large; higher criterion governs.", "QNCS"),
    ("T11", 110, "Enterprise Group & Consolidation", "C. Control & Scope", None, "Associate with enterprise group; truncated group.", "SNA2025"),
    ("T12", 120, "Foreign Ownership & FDI", "D. Residence & International", "fdi_flag", "10% threshold; directional principle.", "BD4"),
    ("T13", 130, "Special Entity Treatment", "C. Control & Scope", "special_entity_flag", "SPV / holding / captive / empty-shell substance test.", "SNA2025"),
    ("T14", 140, "Data Source Hierarchy", "D. Evidence & Governance", None, "Fixed precedence order across sources.", "QNCS"),
    ("T15", 150, "Conflict Resolution", "D. Evidence & Governance", None, "First-match-by-priority; statistical override.", "QNCS"),
    ("T16", 160, "Classification Governance", "D. Evidence & Governance", None, "Technical Classification Committee ruling.", "QNCS"),
    ("T17", 170, "Quality Assurance", "D. Evidence & Governance", None, "Three-layer QA before commit.", "QNCS"),
    ("T18", 180, "Final Classification Record", "D. Evidence & Governance", None, "Full multi-dimensional classification key.", "SNA2025"),
]


def _rule(rid, name, test, domain, logic, output, priority, std, rationale, conf=1.0, inputs=None):
    return {
        "rule_id": rid, "name": name, "test_code": test, "domain": domain, "logic": logic,
        "output": output, "priority": priority, "confidence": conf, "standard_ref": std,
        "rationale": rationale, "inputs_required": inputs or [], "author": "NSO Methodology",
        "approval_status": "APPROVED", "version": "1.0.0",
    }


RULES = [
    # --- T3 Residence (pass-through of sourced residence) ---
    _rule("R-T03-001", "Residence from sourced centre of economic interest", "T3", "residence",
          None, {"residence": {"fact": "residence"}}, 100, "SNA 2025 / BPM6 Ch.4",
          "Residence is taken from the assessed centre of predominant economic interest."),

    # --- T4 ISIC (pass-through of coded principal activity) ---
    _rule("R-T04-001", "Principal activity (ISIC Rev.4)", "T4", "isic_class",
          None, {"isic_class": {"fact": "isic_class"}}, 100, "ISIC Rev.4",
          "Principal activity assigned by largest share of value added."),

    # --- T7 Market vs Non-Market (50% rule) ---
    _rule("R-T07-010", "Government bodies are non-market", "T7", "market_status",
          {"op": "eq", "field": "legal_form_code", "value": "GOV"}, {"market_status": {"const": "NON-MARKET"}},
          10, "GFS 2014", "Government bodies produce non-market output financed by levies."),
    _rule("R-T07-020", "Non-profit not covering costs is non-market", "T7", "market_status",
          {"all": [{"op": "truthy", "field": "is_nonprofit"},
                   {"any": [{"op": "lt", "field": "sales_cover_pct", "value": 50},
                            {"not": {"op": "exists", "field": "sales_cover_pct"}}]}]},
          {"market_status": {"const": "NON-MARKET"}}, 20, "SNA 2025",
          "Non-profit whose sales cover ≤50% of costs is a non-market producer."),
    _rule("R-T07-030", "Sales cover >50% of production costs → market", "T7", "market_status",
          {"op": "gt", "field": "sales_cover_pct", "value": 50}, {"market_status": {"const": "MARKET"}},
          30, "SNA 2025 — 50% rule", "Economically significant prices: sales exceed 50% of production costs."),
    _rule("R-T07-040", "Sales cover ≤50% of production costs → non-market", "T7", "market_status",
          {"op": "exists", "field": "sales_cover_pct"}, {"market_status": {"const": "NON-MARKET"}},
          40, "SNA 2025 — 50% rule", "Sales fail to cover 50% of production costs."),
    _rule("R-T07-100", "Default to market producer", "T7", "market_status",
          None, {"market_status": {"const": "MARKET"}}, 100, "SNA 2025",
          "Absent cost data, a commercial entity is presumed a market producer pending profiling.", conf=0.6),

    # --- T8 Ownership & Effective Control ---
    _rule("R-T08-001", "Effective-control mechanism", "T8", "control_flag",
          None, {"control_flag": {"fact": "representative_control_flag"}}, 100, "SNA 2025 / OECD BD4",
          "Control flag reflects the mechanism (majority vote, board rights, golden share, beneficial-ownership chain) by which the controlling unit exercises effective control."),

    # --- T5 Institutional Sector ---
    _rule("R-T05-010", "Government body → S.13", "T5", "sector_code",
          {"op": "eq", "field": "legal_form_code", "value": "GOV"}, {"sector_code": {"const": "S.13"}},
          10, "SNA 2025", "Ministries, authorities and councils are general government."),
    _rule("R-T05-021", "Central banking → S.121", "T5", "sector_code",
          {"all": [{"op": "truthy", "field": "is_financial"}, {"op": "eq", "field": "isic_class", "value": "6411"}]},
          {"sector_code": {"const": "S.121"}}, 21, "SNA 2025", "Central bank sub-sector."),
    _rule("R-T05-022", "Deposit-taking corporations → S.122", "T5", "sector_code",
          {"all": [{"op": "truthy", "field": "is_financial"}, {"op": "in", "field": "isic_class", "value": ["6419"]}]},
          {"sector_code": {"const": "S.122"}}, 22, "SNA 2025", "Banks / other depository corporations."),
    _rule("R-T05-023", "Fund management → S.126", "T5", "sector_code",
          {"all": [{"op": "truthy", "field": "is_financial"}, {"op": "eq", "field": "isic_class", "value": "6630"}]},
          {"sector_code": {"const": "S.126"}}, 23, "SNA 2025", "Financial auxiliaries (fund managers, brokers)."),
    _rule("R-T05-024", "Holding/captive financial → S.127", "T5", "sector_code",
          {"all": [{"op": "truthy", "field": "is_financial"}, {"op": "in", "field": "isic_class", "value": ["6420", "6430"]}]},
          {"sector_code": {"const": "S.127"}}, 24, "SNA 2025", "Captive financial institutions / SPEs."),
    _rule("R-T05-025", "Insurance → S.128", "T5", "sector_code",
          {"all": [{"op": "truthy", "field": "is_financial"}, {"op": "in", "field": "isic_class", "value": ["6511", "6512", "6520"]}]},
          {"sector_code": {"const": "S.128"}}, 25, "SNA 2025", "Insurance corporations."),
    _rule("R-T05-026", "Pension funding → S.129", "T5", "sector_code",
          {"all": [{"op": "truthy", "field": "is_financial"}, {"op": "eq", "field": "isic_class", "value": "6530"}]},
          {"sector_code": {"const": "S.129"}}, 26, "SNA 2025", "Autonomous pension funds."),
    _rule("R-T05-029", "Other financial corporation → S.12", "T5", "sector_code",
          {"op": "truthy", "field": "is_financial"}, {"sector_code": {"const": "S.12"}},
          29, "SNA 2025", "Financial corporation, sub-sector to be refined."),
    _rule("R-T05-030", "Government-controlled non-market unit → S.13", "T5", "sector_code",
          {"all": [{"op": "eq", "field": "market_status", "value": "NON-MARKET"}, {"op": "truthy", "field": "government_control"}]},
          {"sector_code": {"const": "S.13"}}, 30, "GFS 2014 / SNA 2025",
          "A government-controlled non-market producer (incl. controlled NPI) is general government."),
    _rule("R-T05-035", "Non-profit non-market unit → S.15 (NPISH)", "T5", "sector_code",
          {"all": [{"op": "truthy", "field": "is_nonprofit"}, {"op": "eq", "field": "market_status", "value": "NON-MARKET"}]},
          {"sector_code": {"const": "S.15"}}, 35, "SNA 2025", "Non-market non-profit serving households, not government-controlled."),
    _rule("R-T05-050", "Sole proprietorship → S.14", "T5", "sector_code",
          {"op": "eq", "field": "legal_form_code", "value": "SP"}, {"sector_code": {"const": "S.14"}},
          50, "SNA 2025", "Unincorporated household enterprise."),
    _rule("R-T05-100", "Default → S.11 non-financial corporation", "T5", "sector_code",
          None, {"sector_code": {"const": "S.11"}}, 100, "SNA 2025", "Market producer of goods/non-financial services."),

    # --- T6 Public Sector Boundary ---
    _rule("R-T06-005", "Government body → general government", "T6", "public_private",
          {"op": "eq", "field": "legal_form_code", "value": "GOV"}, {"public_private": {"const": "GG"}},
          5, "GFS 2014", "A ministry, authority or council is part of general government by definition."),
    _rule("R-T06-010", "Government-controlled financial market producer → PUB-FC", "T6", "public_private",
          {"all": [{"op": "truthy", "field": "government_control"}, {"op": "truthy", "field": "is_financial"},
                   {"op": "eq", "field": "market_status", "value": "MARKET"}]},
          {"public_private": {"const": "PUB-FC"}}, 10, "GFS 2014", "Public financial corporation."),
    _rule("R-T06-020", "Government-controlled market producer → PUB-NFC", "T6", "public_private",
          {"all": [{"op": "truthy", "field": "government_control"}, {"op": "eq", "field": "market_status", "value": "MARKET"}]},
          {"public_private": {"const": "PUB-NFC"}}, 20, "GFS 2014", "Public non-financial corporation."),
    _rule("R-T06-030", "Government-controlled non-market producer → GG", "T6", "public_private",
          {"all": [{"op": "truthy", "field": "government_control"}, {"op": "eq", "field": "market_status", "value": "NON-MARKET"}]},
          {"public_private": {"const": "GG"}}, 30, "GFS 2014", "Inside general government."),
    _rule("R-T06-035", "Non-profit non-market unit → NPISH", "T6", "public_private",
          {"all": [{"op": "truthy", "field": "is_nonprofit"}, {"op": "eq", "field": "market_status", "value": "NON-MARKET"}]},
          {"public_private": {"const": "NPISH"}}, 35, "SNA 2025", "Serving households; outside the public sector."),
    _rule("R-T06-040", "Foreign-controlled private corporation → FCC", "T6", "public_private",
          {"all": [{"not": {"op": "truthy", "field": "government_control"}},
                   {"any": [{"op": "truthy", "field": "uci_is_foreign"}, {"op": "gt", "field": "foreign_ownership_pct", "value": 50}]}]},
          {"public_private": {"const": "FCC"}}, 40, "OECD BD4", "Foreign-controlled corporation (FDI sub-flag applies)."),
    _rule("R-T06-050", "Private financial corporation → PRV-FC", "T6", "public_private",
          {"op": "truthy", "field": "is_financial"}, {"public_private": {"const": "PRV-FC"}},
          50, "SNA 2025", "Privately controlled financial corporation."),
    _rule("R-T06-100", "Default → PRV-NFC", "T6", "public_private",
          None, {"public_private": {"const": "PRV-NFC"}}, 100, "SNA 2025", "Private non-financial corporation."),

    # --- T10 Enterprise Size (higher criterion governs) ---
    _rule("R-T10-010", "Large enterprise", "T10", "size_class",
          {"any": [{"op": "gte", "field": "turnover_qar", "value": 150000000}, {"op": "gte", "field": "employment", "value": 250}]},
          {"size_class": {"const": "LARGE"}}, 10, "QNCS / EU 2003/361/EC", "≥250 FTE or > QAR 200m turnover band."),
    _rule("R-T10-020", "Medium enterprise", "T10", "size_class",
          {"any": [{"op": "gte", "field": "turnover_qar", "value": 20000000}, {"op": "gte", "field": "employment", "value": 50}]},
          {"size_class": {"const": "MEDIUM"}}, 20, "QNCS", "50-249 FTE or QAR 30-200m turnover band."),
    _rule("R-T10-030", "Small enterprise", "T10", "size_class",
          {"any": [{"op": "gte", "field": "turnover_qar", "value": 2000000}, {"op": "gte", "field": "employment", "value": 10}]},
          {"size_class": {"const": "SMALL"}}, 30, "QNCS", "10-49 FTE or QAR 3-30m turnover band."),
    _rule("R-T10-100", "Micro enterprise", "T10", "size_class",
          None, {"size_class": {"const": "MICRO"}}, 100, "QNCS", "1-9 FTE; up to QAR 3m turnover."),

    # --- T12 Foreign Ownership & FDI ---
    _rule("R-T12-010", "Round-tripping (ultimately Qatari-controlled)", "T12", "fdi_flag",
          {"all": [{"op": "gte", "field": "foreign_ownership_pct", "value": 10}, {"op": "truthy", "field": "uci_is_government"}]},
          {"fdi_flag": {"const": "ROUND-TRIP"}}, 10, "OECD BD4", "Apparent inward FDI through a non-resident vehicle, ultimately Qatari-controlled."),
    _rule("R-T12-020", "Inward FDI — full control (>50%)", "T12", "fdi_flag",
          {"op": "gt", "field": "foreign_ownership_pct", "value": 50}, {"fdi_flag": {"const": "INWARD-FULL"}},
          20, "OECD BD4", "Foreign majority direct investment — subsidiary."),
    _rule("R-T12-030", "Inward FDI — associate (10-50%)", "T12", "fdi_flag",
          {"op": "gte", "field": "foreign_ownership_pct", "value": 10}, {"fdi_flag": {"const": "INWARD-ASSOC"}},
          30, "OECD BD4", "Direct investment relationship at the 10% threshold; treated as influence."),
    _rule("R-T12-100", "No FDI relationship", "T12", "fdi_flag",
          None, {"fdi_flag": {"const": "NONE"}}, 100, "OECD BD4", "Foreign ownership below the 10% threshold."),

    # --- T13 Special Entity Treatment ---
    _rule("R-T13-010", "Empty-shell — consolidate with parent", "T13", "special_entity_flag",
          {"not": {"op": "truthy", "field": "has_substance"}}, {"special_entity_flag": {"const": "CONSOLIDATE-PARENT"}},
          10, "SNA 2025 §4 (empty-shell rule)", "No premises, employees or autonomy — consolidated with controlling parent."),
    _rule("R-T13-020", "Holding company", "T13", "special_entity_flag",
          {"op": "eq", "field": "isic_class", "value": "6420"}, {"special_entity_flag": {"const": "HOLDING"}},
          20, "ISIC Rev.4 / SNA 2025", "Activities of holding companies (owns equity in subsidiaries)."),
    _rule("R-T13-030", "Trust/fund/SPV", "T13", "special_entity_flag",
          {"op": "eq", "field": "isic_class", "value": "6430"}, {"special_entity_flag": {"const": "SPV"}},
          30, "SNA 2025", "Trusts, funds and similar financial entities."),
    _rule("R-T13-100", "Not a special entity", "T13", "special_entity_flag",
          None, {"special_entity_flag": {"const": "NONE"}}, 100, "SNA 2025", "Substantive operating unit."),
]

# RBAC seed users (password = username + '123' for the demo; change in production)
USERS = [
    ("admin", "System Administrator", "Administrator"),
    ("methodologist", "Lead Methodologist", "Methodologist"),
    ("steward", "Data Steward", "Data Steward"),
    ("classifier", "Classification Analyst", "Classifier"),
    ("reviewer", "Peer Reviewer", "Reviewer"),
    ("auditor", "Statistical Auditor", "Auditor"),
    ("analyst", "Economic Analyst", "Analyst"),
]
